import { CreateRecorrenciaAulaData } from "../schemas/recorrencia-aula.schema";
export declare function createRecorrenciaAula(usuarioId: string, data: CreateRecorrenciaAulaData): Promise<{
    aulas: {
        id: string;
        status: import("../generated/prisma/enums").StatusAula;
        criado_em: Date;
        atualizado_em: Date;
        academia_id: string;
        quadra_id: string;
        inicio_em: Date;
        fim_em: Date;
        observacoes: string | null;
        cliente_id: string | null;
        professor_id: string | null;
        recorrente: boolean;
        recorrencia_id: string | null;
    }[];
    academia: {
        nome: string;
        email: string | null;
        telefone: string | null;
        cidade: string | null;
        cep: string | null;
        slug: string;
        cnpj: string | null;
        endereco: string | null;
        estado: string | null;
        id: string;
        status: import("../generated/prisma/enums").StatusUsuario;
        criado_em: Date;
        atualizado_em: Date;
        limite_jogos_padrao: number;
        periodo_limite_jogos: import("../generated/prisma/enums").PeriodoLimiteJogos;
    };
    quadra: {
        nome: string;
        id: string;
        criado_em: Date;
        atualizado_em: Date;
        academia_id: string;
        descricao: string | null;
        tipo_piso: import("../generated/prisma/enums").TipoPiso;
        coberta: boolean;
        ordem_exibicao: number;
        ativa: boolean;
    };
} & {
    id: string;
    status: import("../generated/prisma/enums").StatusRecorrencia;
    criado_em: Date;
    atualizado_em: Date;
    academia_id: string;
    quadra_id: string;
    professor_id: string | null;
    dias_semana: string;
    data_inicio: Date;
    data_fim: Date | null;
    horario_inicio: string;
    horario_fim: string;
}>;
export declare function listRecorrenciasAula(params: {
    academia_id?: string;
    quadra_id?: string;
    professor_id?: string;
}): Promise<({
    aulas: {
        id: string;
        status: import("../generated/prisma/enums").StatusAula;
        criado_em: Date;
        atualizado_em: Date;
        academia_id: string;
        quadra_id: string;
        inicio_em: Date;
        fim_em: Date;
        observacoes: string | null;
        cliente_id: string | null;
        professor_id: string | null;
        recorrente: boolean;
        recorrencia_id: string | null;
    }[];
    academia: {
        nome: string;
        email: string | null;
        telefone: string | null;
        cidade: string | null;
        cep: string | null;
        slug: string;
        cnpj: string | null;
        endereco: string | null;
        estado: string | null;
        id: string;
        status: import("../generated/prisma/enums").StatusUsuario;
        criado_em: Date;
        atualizado_em: Date;
        limite_jogos_padrao: number;
        periodo_limite_jogos: import("../generated/prisma/enums").PeriodoLimiteJogos;
    };
    quadra: {
        nome: string;
        id: string;
        criado_em: Date;
        atualizado_em: Date;
        academia_id: string;
        descricao: string | null;
        tipo_piso: import("../generated/prisma/enums").TipoPiso;
        coberta: boolean;
        ordem_exibicao: number;
        ativa: boolean;
    };
} & {
    id: string;
    status: import("../generated/prisma/enums").StatusRecorrencia;
    criado_em: Date;
    atualizado_em: Date;
    academia_id: string;
    quadra_id: string;
    professor_id: string | null;
    dias_semana: string;
    data_inicio: Date;
    data_fim: Date | null;
    horario_inicio: string;
    horario_fim: string;
})[]>;
export declare function getRecorrenciaAulaById(id: string): Promise<{
    aulas: {
        id: string;
        status: import("../generated/prisma/enums").StatusAula;
        criado_em: Date;
        atualizado_em: Date;
        academia_id: string;
        quadra_id: string;
        inicio_em: Date;
        fim_em: Date;
        observacoes: string | null;
        cliente_id: string | null;
        professor_id: string | null;
        recorrente: boolean;
        recorrencia_id: string | null;
    }[];
    academia: {
        nome: string;
        email: string | null;
        telefone: string | null;
        cidade: string | null;
        cep: string | null;
        slug: string;
        cnpj: string | null;
        endereco: string | null;
        estado: string | null;
        id: string;
        status: import("../generated/prisma/enums").StatusUsuario;
        criado_em: Date;
        atualizado_em: Date;
        limite_jogos_padrao: number;
        periodo_limite_jogos: import("../generated/prisma/enums").PeriodoLimiteJogos;
    };
    quadra: {
        nome: string;
        id: string;
        criado_em: Date;
        atualizado_em: Date;
        academia_id: string;
        descricao: string | null;
        tipo_piso: import("../generated/prisma/enums").TipoPiso;
        coberta: boolean;
        ordem_exibicao: number;
        ativa: boolean;
    };
} & {
    id: string;
    status: import("../generated/prisma/enums").StatusRecorrencia;
    criado_em: Date;
    atualizado_em: Date;
    academia_id: string;
    quadra_id: string;
    professor_id: string | null;
    dias_semana: string;
    data_inicio: Date;
    data_fim: Date | null;
    horario_inicio: string;
    horario_fim: string;
}>;
export declare function cancelarRecorrenciaAula(usuarioId: string, recorrenciaId: string): Promise<{
    aulas: {
        id: string;
        status: import("../generated/prisma/enums").StatusAula;
        criado_em: Date;
        atualizado_em: Date;
        academia_id: string;
        quadra_id: string;
        inicio_em: Date;
        fim_em: Date;
        observacoes: string | null;
        cliente_id: string | null;
        professor_id: string | null;
        recorrente: boolean;
        recorrencia_id: string | null;
    }[];
    academia: {
        nome: string;
        email: string | null;
        telefone: string | null;
        cidade: string | null;
        cep: string | null;
        slug: string;
        cnpj: string | null;
        endereco: string | null;
        estado: string | null;
        id: string;
        status: import("../generated/prisma/enums").StatusUsuario;
        criado_em: Date;
        atualizado_em: Date;
        limite_jogos_padrao: number;
        periodo_limite_jogos: import("../generated/prisma/enums").PeriodoLimiteJogos;
    };
    quadra: {
        nome: string;
        id: string;
        criado_em: Date;
        atualizado_em: Date;
        academia_id: string;
        descricao: string | null;
        tipo_piso: import("../generated/prisma/enums").TipoPiso;
        coberta: boolean;
        ordem_exibicao: number;
        ativa: boolean;
    };
} & {
    id: string;
    status: import("../generated/prisma/enums").StatusRecorrencia;
    criado_em: Date;
    atualizado_em: Date;
    academia_id: string;
    quadra_id: string;
    professor_id: string | null;
    dias_semana: string;
    data_inicio: Date;
    data_fim: Date | null;
    horario_inicio: string;
    horario_fim: string;
}>;
//# sourceMappingURL=recorrencia-aula.service.d.ts.map